// <auto-generated />
using CadastroPessoas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroPessoas.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201026181717_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroPessoas.Models.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataNascimento")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 48)))
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("salario")
                        .HasColumnType("money");

                    b.HasKey("id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("CadastroPessoas.Models.Telefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_pessoa");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(07)");

                    b.HasKey("id");

                    b.HasIndex("id_pessoa");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("CadastroPessoas.Models.Telefone", b =>
                {
                    b.HasOne("CadastroPessoas.Models.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("id_pessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
